---
# letsencrypt doesn't recommend using the Ubuntu-provided letsencrypt package
# https://github.com/certbot/certbot/issues/3538
# They do recommend using certbot from their PPA for Xenial
# https://certbot.eff.org/#ubuntuxenial-nginx

- name: install software-properties-common
  apt:
    name: software-properties-common
    state: latest
    update_cache: yes
  become: true

- name: install certbot
  apt:
    name: certbot
    state: latest
    update_cache: yes
  become: true

- name: ensure letsencrypt acme-challenge path
  file:
    path: "{{ ssl_webroot_path }}"
    state: "directory"
    mode: 0755
  become: true

- name: create (or renew) letsencrypt ssl cert
  command: "{{ letsencrypt_command }}"
  become: true

- name: reload nginx to make sure latest configs are in use
  service:
    name: nginx
    state: reloaded
  become: true

- name: setup a cron to attempt to renew the SSL cert every 15ish days
  cron:
    name: "renew letsencrypt cert"
    minute: "0"
    hour: "0"
    day: "1,15"
    job: "certbot renew --renew-hook='systemctl reload nginx'"
  become: true

# This cronjob would attempt to renew the cert twice a day but doesn't have our required --renew-hook
- name: make sure certbot's cronbjob is not present
  file:
    path: /etc/cron.d/certbot
    state: absent
  become: true

# Same thing here.  Let me automate how I wanna automate plz.
- name: make sure certbot's systemd services are disabled
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items:
    - "certbot.service"
    - "certbot.timer"
  become: true
